services:
  recipe-app:
    networks:
      - recipe-network
  recipe-db:
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - recipe-network

volumes:
  db-data:

networks:
  recipe-network:
