# This Dockerfile is used for integration tests
FROM maven:3.9.6 as build

RUN mkdir /recipes

# Copy pom and resolve dependencies
# This reduces execution time for mvn verify on subsequent calls
COPY ./pom.xml /recipes/
WORKDIR /recipes

RUN mvn dependency:resolve-plugins 
RUN mvn dependency:resolve

# Finally copy ITs as a last layer
COPY ./src /recipes/src
RUN mvn clean package

FROM openjdk:21
COPY --from=build /recipes/target/recipe-0.0.1-SNAPSHOT.jar /recipes.jar

CMD ["java",  "-jar", "/recipes.jar"]