services:
  test-client:
    command: ["mvn", "verify"]
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      recipe-app:
        condition: service_healthy
    networks:
      - recipe-network-test
    environment:
      - SPRING_CONFIG_LOCATION=classpath:application.yml,/run/secrets/.application.ssh-keys.yml
    secrets:
      - .application.ssh-keys.yml

  recipe-app:
    networks:
      - recipe-network-test
    healthcheck:
      test: "curl -i localhost:8080/DOES_NOT_EXIST | grep 401 || exit 1"
      interval: 10s
      retries: 5
      timeout: 30s
  recipe-db:
    networks:
      - recipe-network-test

networks:
  recipe-network-test:
