services:
  recipe-app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: recipe-app
    depends_on:
      recipe-db:
        condition: service_healthy
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./recipez
        target: /recipes
    environment:
      - DB_HOST=recipe-db
      - DB_PORT=3306
      - DB_USER=recipeappadmin
      - DB_NAME=recipedb
      - REL_BASE_URL=http://localhost:8080
      - SPRING_CONFIG_LOCATION=classpath:application.yml,/run/secrets/.application.ssh-keys.yml,/run/secrets/.application.datasource.yml
    secrets:
      - .application.ssh-keys.yml
      - .application.datasource.yml

  recipe-db:
    build:
      dockerfile: Dockerfile_DB
      context: .
    container_name: recipe-db
    healthcheck:
      interval: 10s
      retries: 3
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized",
        ]
      timeout: 30s
    environment:
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/db_password_root
      - MARIADB_USER=recipeappadmin
      - MARIADB_DATABASE=recipedb
      - MARIADB_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password_root
      - db_password

secrets:
  db_password_root:
    file: db_password_root
  db_password:
    file: db_password
  .application.ssh-keys.yml:
    file: .application.ssh-keys.yml
  .application.datasource.yml:
    file: .application.datasource.yml
