apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -f docker-compose.local.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: recipe-app
  name: recipe-app
spec:
  type: ClusterIP
  ports:
    - name: "http"
      port: 80
      targetPort: 8080
  selector:
    io.kompose.service: recipe-app
