spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:recipedb;DATABASE_TO_UPPER=false;MODE=MySQL;NON_KEYWORDS=USER
    username: sa
    password:
  sql:
    init.mode: always
    # Use this option to provide initial data
    # E.g.: place data.sql in the same directory and use <sql-script-location>=data.sql
    # init.data-locations: classpath:<sql-script-location>
  jpa:
    hibernate.ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
    hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

  jwt.private.key: optional:classpath:pkcs8.id_rsa
  jwt.public.key: optional:classpath:id_rsa.pem
