name: GitHub Actions Continous Integration
run-name: ${{ github.actor }}
on:
  pull_request:
    types: [opened, reopened]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hoverkraft-tech/compose-action@v2.0.0
        with:
          compose-file: ["./docker-compose.yml", "./docker-compose.test.yml"]
