name: GitHub Actions Continous Integration
run-name: ${{ github.actor }}

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, edited]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run tests
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml up --build
